# Generated by Django 5.1 on 2024-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='total_projects',
            field=models.IntegerField(null=True),
        ),
    ]
