# Generated by Django 5.1 on 2024-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_info_total_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='comany_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
