# Generated by Django 5.1 on 2024-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_experience_comany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='google_form',
            field=models.TextField(null=True),
        ),
    ]
